title: dawn | A small design and development studio in Madison, WI
email: hi@dawnlabs.io
description: Dawn is a small design and development studio based in Madison, Wisconsin. We help companies and startups build products for the web.
url: dawnlabs.io # the base hostname & protocol for your site
twitter_username: dawn_labs
github_username:  dawnlabs
# facebook_username:
sass:
  sass_dir: _sass
  style: compressed
# Build settings
markdown: kramdown
